tmdt/tmdt/Areas/admin/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace tmdt.Areas.admin.Controllers
{
    public class DefaultController : Controller
    {
        // GET: admin/Default
        public ActionResult Index()
        {
            return View();
        }
    }
}

tmdt/tmdt/Areas/admin/Controllers/spsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using tmdt.Models;

namespace tmdt.Areas.admin.Controllers
{
    public class spsController : Controller
    {
        private QLBH123Entities db = new QLBH123Entities();

        // GET: admin/sps
        public ActionResult Index()
        {
            var sps = db.sps.Include(s => s.loaisp);
            return View(sps.ToList());
        }

        // GET: admin/sps/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sp sp = db.sps.Find(id);
            if (sp == null)
            {
                return HttpNotFound();
            }
            return View(sp);
        }

        // GET: admin/sps/Create
        public ActionResult Create()
        {
            ViewBag.maloai = new SelectList(db.loaisps, "ma", "ten");
            return View();
        }

        // POST: admin/sps/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ma,ten,mota,maloai,anhnho,anh1,anh2,anh3,tskt,tieubieu,trangthai,xoa,hang,gia,khuyenmai,ngaydang,dvt")] sp sp)
        {
            if (ModelState.IsValid)
            {
                db.sps.Add(sp);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.maloai = new SelectList(db.loaisps, "ma", "ten", sp.maloai);
            return View(sp);
        }

        // GET: admin/sps/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sp sp = db.sps.Find(id);
            if (sp == null)
            {
                return HttpNotFound();
            }
            ViewBag.maloai = new SelectList(db.loaisps, "ma", "ten", sp.maloai);
            return View(sp);
        }

        // POST: admin/sps/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ma,ten,mota,maloai,anhnho,anh1,anh2,anh3,tskt,tieubieu,trangthai,xoa,hang,gia,khuyenmai,ngaydang,dvt")] sp sp)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sp).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.maloai = new SelectList(db.loaisps, "ma", "ten", sp.maloai);
            return View(sp);
        }

        // GET: admin/sps/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sp sp = db.sps.Find(id);
            if (sp == null)
            {
                return HttpNotFound();
            }
            return View(sp);
        }

        // POST: admin/sps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            sp sp = db.sps.Find(id);
            db.sps.Remove(sp);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

tmdt/tmdt/Areas/admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="@Url.Action("Index","Default")">Trang chủ <span class="sr-only">(current)</span></a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Quản lý sản phẩm <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index","sps")">Danh sách sản phẩm</a></li>
                            <li><a href="@Url.Action("Create","sps")">Thêm sản phẩm mới</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="@Url.Action("Index","loaisps")">Danh sách loại sản phẩm</a></li>
                            <li><a href="@Url.Action("Create","loaisps")">Thêm loại sản phẩm mới</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Quản lý tin tức <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Danh sách tin</a></li>
                            <li><a href="#">Thêm tin mới</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Danh sách chuyên mục</a></li>
                            <li><a href="#">Thêm chuyên mục</a></li>
                        </ul>

</ul>
                <ul class="nav navbar-nav navbar-right">
                    @*<li><a href="#">Link</a></li>*@
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Thông tin user</a></li>
                            <li><a href="#">Thay đổi mật khẩu</a></li>
                            @*<li><a href="#">Something else here</a></li>*@
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Thoát</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>